### ISSUE TITLE
Document that we require Apollo Server library versions >=2.14 for the plugin to be compatible

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/newrelic-node-apollo-server-plugin#133]
Formal support for the `willResolveField` plugin hook that we’re relying on wasn’t introduced until apollo-server@2.14 -- https://github.com/apollographql/apollo-server/blob/main/CHANGELOG.md#v2140

Using earlier versions can result in errors such as failing due to an “didEndHook is not a function” error when making any query. Hypothesis is this is currently causing issues for an internal user on 2.9.16 where theres no clear cause of the error just a 500 status code in the logs / sent up to New Relic.

We discovered all this during our initial prototyping (see the "GraphQL Plugin Open Questions and Next Steps" document internally) but seems we failed to document in the readme / with the real implementation. You can see our versioned tests have >=2.14.

**Comment by rr0214** [comment]
Add to README and to capability section in NR docs

**Comment by jordigh** [comment]
Other PR is here: https://github.com/newrelic/docs-website/pull/9056
