### ISSUE TITLE
All transactions marked under /graphql. With preregisted newrelic / ts-node registrations.

### ISSUE THREAD

**Issue by Scong** [newrelic/newrelic-node-apollo-server-plugin#143]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

All transactions marked under /graphql. 

When node new relic pre require @newrelic/apollo-server-plugin with 

`node -r newrelic -r ts-node/register  -r tsconfig-paths/register ./src/index.ts`
 
![image](https://user-images.githubusercontent.com/4022295/138350271-9134ad36-a6cc-41b1-996e-cc091217c6a9.png)

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

Expected query / transaction paths to be provided based off of the incoming request.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

New relic is receiving requests, it just seems to not be receiving the functionality provided by plugin

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
node -r newrelic -r ts-node/register  -r tsconfig-paths/register ./src/index.ts

I believe this happens with standard config with apollo server express. I have removed all of our plugins except for newrelic apollo server. It is possible tsconfig-paths could be affecting something, will likely continue looking into it. 
```
const newRelicPlugin = require('@newrelic/apollo-server-plugin')
import { ApolloServer, AuthenticationError } from "apollo-server-express";

plugins: [
      newRelicPlugin,
  ]
```
## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
Node version 14.17.6

"@newrelic/apollo-server-plugin": "^1.1.0",
"apollo-server-caching": "^3",
 "apollo-server-express": "^3",
 "apollo-server-plugin-response-cache": "^3",

* ex: Browser name and version:
* ex: Node version: 
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
Looks separate from the other issues here. Have generally tried variations of this. If I don't preregister newrelic nothing is sent, I can use ts-node similarly to the command I have above with the same issue.

I think this is different than https://github.com/newrelic/newrelic-node-apollo-server-plugin/issues/117 as I never see the paths. 

I'll file a ticket through support, just incase this ends up being a me thing.

**Comment by bizob2828** [comment]
@Scong I confirmed you logged a ticket with support.  I'm going to close this but have you tried to change the `-r` order?

```
node -r ts-node/register -r tsconfig-paths/register -r newrelic ./src/index.ts
```
