### ISSUE TITLE
Add a test (integration or versioned) that exercises via TypeScript

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/newrelic-node-apollo-server-plugin#150]
While less likely to break again in the future, current TypeScript type testing is limited to asserting things are set as expected. That doesn't mean that actually work imported into a TypeScript project.

We should have some tests that are actually built in TypeScript to verify everything is compatible.

**Comment by jsumners-nr** [comment]
🤷‍♂️ yes? I really don't know what we'd need to do to prove TS support.

**Comment by bizob2828** [comment]
If you look in the history of this repo, we've messed this up a few times which is why this was logged originally
