### ISSUE TITLE
Log stops after a few minutes of starting

### ISSUE THREAD

**Issue by tinchogon34** [newrelic/newrelic-node-apollo-server-plugin#166]
## Description

Hi, I'm using this plugin with apollo-server-express.

After restarting the server the plugin starts working ok and I can see transactions in New Relic web, but after a few minutes (almost 5) new relic does not show me nothing more.

When this happens, I can see a bunch of this lines in new relic agent log file:

{"v":0,"level":40,"name":"newrelic","hostname":"....","pid":19,"time":"2022-01-26T14:36:32.179Z","msg":"Active transaction when creating non-nested transaction","component":"tracer","transaction":{"id":"f0dfce6aeccdc9e9","name":"Expressjs/POST//batch/query/GetLead/lead/query/GetLead/lead"},"segment":"GraphQL/resolve/ApolloServer/lead.client.category"}

I couldn't find any information related to this message. Could you help me?

Sorry in advance if it's not a bug.

Thanks!

**Comment by bizob2828** [comment]
Hi @tinchogon34, sorry for the delayed response. For issues like this, I recommend leveraging our support team over at support.newrelic.com which can help deep-dive into solving the problem.  They will also ask to collect the necessary information which may or may not be sensitive (such as logs).

**Comment by shemlick** [comment]
I believe I am seeing the same issue. I will get several logs saying "Active transaction when creating non-nested transaction" and then I will start to get logs saying "No active segment found at query start. Not recording." After this nothing is getting recorded in new relic until I restart my application. I'm only seeing this error when I use just the new relic agent and the new relic apollo server plugin.

**Comment by bizob2828** [comment]
Hi @shemlick, can you provide a reproduction case?  I realized I never asked @tinchogon34 last time but if one of y'all could do so we may be able to identify and fix without going through our technical support channels.

**Comment by shemlick** [comment]
Hi @bizob2828 I'm working on creating a reproduction case now. Basically the issue seems to occur in our app whenever we refresh a page that is making a graphql call to our apollo server. It appears we would enter [this block](https://github.com/newrelic/node-newrelic/blob/main/lib/transaction/tracer/index.js#L108) with a segment that was already ended and once that happened it would never get out of that state. I tweaked the if statement locally to account for "ended" segments by changing it to the following and that seemed to fix the issue

`if (segment && !segment._isEnded()) {`

**Comment by michaelgoin** [comment]
@shemlick Thank you for working on a repro case. That will help a ton. 

Can you share the name of the segment that gets propagated here? A repro case will be most helpful but this may give some early hints.

We need to track down which segment (and why) is getting incorrectly propagated across requests. 

Thanks!

**Comment by shemlick** [comment]
The segment is named "GraphQL/operation/ApolloServer/query/<anonymous>/userCount"

I haven't been able to reproduce the issue outside of our codebase yet. It seems to only be an issue when we use schema stitching and the call is made to the master apolloServer. It also appears that I only run into this issue when 2 or more calls are batched together.

**Comment by Whassup** [comment]
I have found that I have the same issue I have a project using express and apollo. After about 5 minutes transactions stop being sent to new relic.

I found I get this issue when I have this config to enable undici instrumentation in the new relic config.

newrelic.js
```
  feature_flag: {
    /**
     * Enable instrumentation for the undici http client: https://github.com/newrelic/node-newrelic/pull/921
     */
    undici_instrumentation: true,
    undici_async_tracking: false,
  },
```

@shemlick out of interset are you using similar config?

These are the two common new relic logs I see 
```
No transaction found for custom attributes.
Active transaction when creating non-nested transaction
```

**Comment by shemlick** [comment]
@Whassup I am not enabling undici instrumentation but I am using express and apollo. I do remember seeing the "Active transaction when creating non-nested transaction" log getting printed when this would occur

**Comment by Whassup** [comment]
I searched both new relic org's code base and cant find any code releated to this message `Active transaction when creating non-nested transaction` can anyone provide more detail on causes that error and if its related?

**Comment by michaelgoin** [comment]
I'd recommend anyone who runs into "Active transaction when creating non-nested transaction" to engage with the team over at support.newrelic.com so we can gather more sensitive information.

This occurs when state has been incorrectly propagated between separate requests. These sorts of issues can be really hard to get to the bottom of without a reproduction. Sometimes they are introduced based on injected third-party modules/plugins/etc. doing pooling or other asynchronous actions that require extra handling. If you can come up with minimal repro, that will greatly expedite our ability resolve these issues.
