### ISSUE TITLE
Add semver check that returns no-op for versions < 2.14 of apollo-server

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/newrelic-node-apollo-server-plugin#17]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

We are only guaranteed to work (at least for now) with v2.14 of apollo-server and greater. Needs to be defensive.

How does this play with middleware-packages? for example, the express middleware package?

**Comment by michaelgoin** [comment]
Realizing this may or may not be possible... depends on if the middleware all reference apollo-server in which case we could prob attempt w/ a try/catch. All the libraries seem to follow consistent versioning (at least currently) but we won't really know which library we are being used with. Similar problem for the peer-dep (which we were hoping to avoid).

So if it doesn't work out, we'll just have to document well.

**Comment by bizob2828** [comment]
feels like we can close but waiting for @michaelgoin to be present in grooming to discuss

**Comment by michaelgoin** [comment]
Given this has been a non-issue thus far, and the issues involved in checking across the various modules, going to close this out as not being important enough to tackle for the investment (at least currently).
