### ISSUE TITLE
Apollo federation and subgraph configuration

### ISSUE THREAD

**Issue by douglas-wang** [newrelic/newrelic-node-apollo-server-plugin#188]
## Description
We have setup this plugin in apollo federated gateway and subgraphs.
We have them running in one server - 1 gateway + 4 subgraphs

The problem is that newrelic stopped working after apollo federations.
So we started to introduce this plugin but still the same.

Here is some of the code structure we have.
```
|
  |-- gateway
    |-- server.ts
  |-- subgraphs
    |-- subgraph1
      |-- server.ts
    |-- subgraph2
      |-- server.ts
  newrelic.js
```

gateway/server.ts file
```typescript
import dotenv from 'dotenv'
dotenv.config()

import { ApolloGateway } from '@apollo/gateway'
import createPlugin from '@newrelic/apollo-server-plugin'
import { ApolloServerPluginLandingPageGraphQLPlayground } from 'apollo-server-core'
import { ApolloServer } from 'apollo-server-express'
import cors from 'cors'
import express from 'express'
import { readFileSync } from 'fs'
import { graphqlUploadExpress } from 'graphql-upload'
import { createServer } from 'http'
import path from 'path'

const app = express()
const gateway = new ApolloGateway()
const server = new ApolloServer({
    gateway,
    introspection: process.env.ENABLE_INTROSPECTION_QUERIES === 'true',
    plugins: [
      ApolloServerPluginLandingPageGraphQLPlayground(),
      usageReportingPlugin(),
      createPlugin(),
    ],
  })
  const httpServer = createServer(app)
  await server.start()

  server.applyMiddleware({
    app,
    path: '/graphql',
  })

  httpServer.listen(process.env.PORT, () => {
    console.log(`🚀 Gateway ready 🚀`)
  })
```

newrelic.js
```js
'use strict'
require('dotenv').config()
/**
 * New Relic agent configuration.
 *
 * See lib/config/default.js in the agent distribution for a more complete
 * description of configuration variables and their potential values.
 */

const appName = process.env.NEW_RELIC_APP_NAME

exports.config = {
  /**
   * Array of application names.
   */
  app_name: [appName],
  /**
   * Your New Relic license key.
   */
  license_key: process.env.NEW_RELIC_LICENSE_KEY,
  logging: {
    /**
     * Level at which to log. 'trace' is most useful to New Relic when diagnosing
     * issues with the agent, 'info' and higher will impose the least overhead on
     * production applications.
     */
    level: 'info',
  },
  /**
   * When true, all request headers except for those listed in attributes.exclude
   * will be captured for all traces, unless otherwise specified in a destination's
   * attributes include/exclude lists.
   */
  allow_all_headers: true,
  attributes: {
    /**
     * Prefix of attributes to exclude from all destinations. Allows * as wildcard
     * at end.
     *
     * NOTE: If excluding headers, they must be in camelCase form to be filtered.
     *
     * @env NEW_RELIC_ATTRIBUTES_EXCLUDE
     */
    exclude: [
      'request.headers.cookie',
      'request.headers.authorization',
      'request.headers.proxyAuthorization',
      'request.headers.setCookie*',
      'request.headers.x*',
      'response.headers.cookie',
      'response.headers.authorization',
      'response.headers.proxyAuthorization',
      'response.headers.setCookie*',
      'response.headers.x*',
    ],
  },
}
```

subgraph1/server.ts
```ts
  const app = express()

  const server = new ApolloServer({
    schema: config.schema,
    plugins: [
      ApolloServerPluginLandingPageGraphQLPlayground(),
      ApolloServerPluginInlineTrace(),
      usageReportingPlugin(),
      createPlugin(),
    ],
  })

  if (config.requiresUploadPlugin) {
    app.use(graphqlUploadExpress())
  }

  const httpServer = createServer(app)
  await server.start()

  server.applyMiddleware({
    app,
    path: '/graphql',
  })
```

package.json
```json
{
...
  "scripts": {
    "dev:subgraph:subgraph1": "ts-node-dev -r tsconfig-paths/register ./subgraph1/server.ts",
    "dev:subgraph:subgraph2": "ts-node-dev -r tsconfig-paths/register ./subgraph2/server.ts",
    "dev:supergraph": "ts-node-dev -r tsconfig-paths/register ./gateway/server.ts",
    "dev": "concurrently -n subgraph:,supergraph\"npm run dev:subgraph:*\" \"npm run dev:supergraph\""
  }
}
```

## Expected Behavior

Expected to see the reports in newrelic or log file locally.

## Your Environment

node 16
"@apollo/gateway": "^0.50.0",
"@apollo/subgraph": "^0.4.0",
"@newrelic/apollo-server-plugin": "^1.2.2",
"apollo-server": "^3.6.7",
"apollo-server-express": "^3.6.7",
"newrelic": "^8.9.1",

## Additional context
I got `undefined` for that first parameter: `instrumentationApi`
<img width="419" alt="image" src="https://user-images.githubusercontent.com/81151269/160804135-6496a944-87b0-4c24-829b-312b19fcb1d4.png">

**Comment by garbados** [comment]
I believe the issue is that you are calling createPlugin prior to providing it as a plugin. The example code from our plugin's documentation indicates you should leave it to Apollo to invoke the plugin, like so:

```js
// index.js
const plugin = require('@newrelic/apollo-server-plugin')

// imported from supported module
const server = new ApolloServer({
  typeDefs,
  resolvers,
  plugins: [plugin]
})
```

Let us know if you continue to have issues!

**Comment by garbados** [comment]
Ah, my apologies. It looks like that's not the solution. Let me look deeper and get back to you...

**Comment by garbados** [comment]
So, it looks like the New Relic agent isn't loading, which causes that `instrumentationApi` parameter to be undefined. My team feels you should reach out to our technical support team to help you parse out your logs and ensure the agent is being loaded properly.

**Comment by douglas-wang** [comment]
@garbados, we've already tried to reach out to [vwilson@newrelic.com](mailto:vwilson@newrelic.com) for our issues.

**Comment by dkowalec** [comment]
Is Apollo Federation supported on the Acquia Cloud platform?

**Comment by dkowalec** [comment]
## [UPDATE]
Acquia executive leadership for enterprise has confirmed they do not support Apollo Federation with New Relic. Similar limitations with distributed tracing issues. They were did update their documentation 😂 which is the furthers I have gotten.
* https://docs.acquia.com/cloud-platform/monitor/apm/configuring-new-relic/#compatibility-statement

> https://discuss.newrelic.com/t/node-new-relic-agent-not-starting-using-apollo-federation/181282

## Suggestion
I suggest New Relic leadership applies pressure and works out something with the major Drupal hosting platform if you would like customers on Acquia to continue to leverage your platform for monitoring.

## Compatibility statement
Cloud Platform is compatible with the Application Monitoring services provided by New Relic. Acquia doesn’t support New Relic Infrastructure Monitoring services, Log Monitoring services, or any plug-ins.
> Cloud Platform isn’t compatible with [New Relic APM’s Distributed Tracing (https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/get-started/introduction-distributed-tracing) feature.
> Acquia can’t make changes to the New Relic agent on a per-client basis.
> Acquia doesn’t support the installation of New Relic on any non-web infrastructure. While New Relic routinely makes updates to their services and periodically adds new features, Acquia will update versions of this service running on Acquia Cloud twice annually. This allows Acquia to ensure new logic in New Relic’s PHP monitoring agent has had several months to stabilize before introducing it onto Cloud Platform.

Weak sauce on their part so I hope someone can fix this partnership.

fyi @douglas-wang @garbados @bizob2828

**Comment by brnhensley** [comment]
Link to Community forum post about this: https://discuss.newrelic.com/t/node-new-relic-agent-not-starting-using-apollo-federation/181282
