### ISSUE TITLE
Transactions named "Fastify/POST//*" or "Fastify/GET//*" when validation is cached.

### ISSUE THREAD

**Issue by tomvardasca** [newrelic/newrelic-node-apollo-server-plugin#189]
## Description

Most of the transactions are named as "Fastify/POST//*" or "Fastify/GET//*". The is still a residual number of transactions with the correct names.
This issue is due to the Transaction naming on the [validationDidStart](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#validationdidstart) Apollo Server event. And as stated in the documentation: `Like parsingDidStart, this event does not fire if a request's document is already available in Apollo Server's cache (only successfully validated documents are cached by Apollo Server).`

@newrelic/apollo-server-plugin@1.2.3

## Expected Behavior

Have all the transactions with correct names.

## Your Environment

Node version: 16.14
Apollo server version: 3.6
Fastify version: 3.27
@newrelic/apollo-server-plugin version 1.2.3

## Sugestion

Move the Transaction naming logic to the [didResolveSource](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#didresolvesource) Apollo Server event.

**Comment by bizob2828** [comment]
Thanks for logging this @tomvardasca, we will prioritize accordingly.  Unfortunately we cannot use `didResolveSource` as we rely on the parsed document for naming.

**Comment by tomvardasca** [comment]
But we have the document name on that event. Did some testing and was able to use it.
Maybe I am missing something.

**Comment by bizob2828** [comment]
> didResolveSource

We're relying on the document AST as we traverse it to properly name operations/transactions.  The earliest we can guarantee that is in `validationDidStart` but overlooked the fact this hook point doesn't always fire.

**Comment by bizob2828** [comment]
> But we have the document name on that event. Did some testing and was able to use it. Maybe I am missing something.

@tomvardasca We're relying on the document AST as we traverse it to properly name operations/transactions. The earliest we can guarantee that is in validationDidStart but overlooked the fact this hook point doesn't always fire.

**Comment by bizob2828** [comment]
@tomvardasca I just released version 1.3.0, it should fix the issue you have described.
