### ISSUE TITLE
Include customAttributes on the Segments/Spans

### ISSUE THREAD

**Issue by KGAdamCook** [newrelic/newrelic-node-apollo-server-plugin#199]
## Is your feature request related to a problem? Please describe.
I wish I could filter my metric queries (Top 10 Slowest Operations) by specified custom attributes, such as the "apolloclient-graphql-name"

## Feature Description
Include custom attributes set via newrelic.addCustomAttributes on the segments and spans

## Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

## Additional context
In my codebase I am already calling `newrelic.addCustomAttributes({ clientName: req.headers['apollographql-client-name'] })`, however this doesn't seem to get added to any Span events that this plugin creates. 

## Priority
Please help us better understand this feature request by choosing a priority from the following options:
Nice to Have

**Comment by coreyarnold** [comment]
Thanks @KGAdamCook for this report. We will take a look at this and see what we can do. Can you provide a little more code context about where/when you're adding custom attributes in your code?

**Comment by KGAdamCook** [comment]
When we initialise our ApolloServer we use a custom `context` function as shown here: https://www.apollographql.com/docs/apollo-server/data/resolvers/#the-context-argument. 

Inside of our context function is where I am adding the newrelic.addCustomAttributes({ });

**Comment by bizob2828** [comment]
> I would have hoped we could just use the already provided API of `newrelic.addCustomAttributes()`, but sure, if we have to add them another way too that would be fine. 
> 
> 
> 
> Yeah I had just thought it would be for the operation span/segments. 

We don't intend changing that, it's just that API works different in this context. We can look into more and provide some guidance/solutions.

**Comment by jordigh** [comment]
Closed by #249

**Comment by bizob2828** [comment]
Hi @KGAdamCook this work has been released in [3.1.0](https://github.com/newrelic/newrelic-node-apollo-server-plugin/releases/tag/v3.1.0) of the plugin. Take a look at the release notes regarding how you would do this
