### ISSUE TITLE
lambda deployment not able to get Operation Metrics and Field Resolve Metrics

### ISSUE THREAD

**Issue by Blankll** [newrelic/newrelic-node-apollo-server-plugin#201]
# Not able to get Operation Metrics and Field Resolve Metrics from lambda
## Description
when deploy apollo-server-lambda by a lambda and add this plugin as bellow:
```ts
const newRelicPlugin = createPlugin();
const graphqlServer = new ApolloServer({
...
  plugins: [newRelicPlugin],
});
```
I can only find this app under `lambda functions` instead `APM`, and no  `Operation Metrics` and `Field Resolve Metrics` under `lambda functions`
so can't execute any query mentioned in README like:
```
FROM Metric
SELECT average(newrelic.timeslice.value) * 1000 WHERE appName = '[YOUR APP NAME]' WITH METRIC_FORMAT 'GraphQL/resolve/ApolloServer/{field}' FACET field LIMIT 10
```
## Expected Behavior
I can see the app &  Metrics under `APM` or Metrics listed under `lambda functions`

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Your Environment
lambda runtime: Node.js 14.x
Instrumented by cloudformation

"@newrelic/apollo-server-plugin": "^1.3.0",
"@vendia/serverless-express": "^4.8.0",
"apollo-server-lambda": "^3.8.1",
"graphql": "^15.8.0",

**Comment by bizob2828** [comment]
Hi @Blankll running in AWS lambda is a different UX.  As you found all execution data is within the lambda functions.  The README for the apollo server plugin assumes you're not in a serverless environment.  Here are the docs that describe [Monitoring Lambda](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/monitoring-aws-lambda-serverless-monitoring/), and [Lambda monitoring architecture](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/architecture/).  I notice it doesn't explicitly call it out but I asked the serverless team internally and they state metrics are not a feature that is supported within lambda executions.  With all that being said, unfortunately there's nothing this plugin can do to get the metrics loaded into New Relic One.  However, you can still get the span data within distributed tracing which will show you APM data around how long operations and resolvers are taking, would that be helpful?

**Comment by Blankll** [comment]
Thanks for your reply @bizob2828, so this plugin(or say NewRelic lambda monitoring) actually does not have graphql Resolver level monitoring support at this moment, but by enabling lambda's distribute tracing, we can get the HTTP request monitoring data(eg. how long the request is taking) from distribute tracing?
And just saw that README listed `apollo-server-lambda` as the supported framework, if my assumption above is true, is it better to remove it to eliminate confusion for the people like me?

**Comment by bizob2828** [comment]
This plugin does support apollo-server-lambda.  It also does have graphql resolver level monitoring in the form of spans/segments.  The only thing It doesn't have is metrics which applies to any Node.js code running our agent or the apollo server plugin.  If you're trying to determine how to get what you need, I recommend leveraging our support team over at [support.newrelic.com](https://support.newrelic.com].  They can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs).

**Comment by bizob2828** [comment]
This request cannot be addressed as is because it's an architectural change in the New Relic ecosystem to support loading of metrics from any APM app using a language agent.
