### ISSUE TITLE
HTTP 502 timeout on graphql query is not showing up in distributed trace for developer troubleshooting

### ISSUE THREAD

**Issue by TraGicCode** [newrelic/newrelic-node-apollo-server-plugin#208]
## Description

We have set a timeout on the nodejs httpserver of 30 seconds.  When a graphql query takes too long a 502 http timeout status code is returned.  This is causing the distributed trace to not show the exact transaction and lines of code that caused the timeout.  Is this expected?  This makes it hard to troubleshoot where the problematic piece of code lies since all webrequests hit graphql via the same endpoint (http://localhost/graphql).

## Expected Behavior

When a 502 gateway timeout occurs, i expect the distributed trace to show me the exact transaction and lines of code that were executing so i can troubleshoot where the performance issue lies.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

@newrelic/apollo-server-plugin 1.3.0
newrelic 8.10.0
apollo-server-core 3.7.0
apollo-server-errors3.3.1
apollo-server-express 3.7.0
graphql 16.4.0

## NewRelic Case Number

00052306

**Comment by bizob2828** [comment]
Hi @TraGicCode i see you referenced a case number.  This will be your best chance in getting assistance with your issue.  If you are still having a problem after working it with our technical support, feel free to reopen
