### ISSUE TITLE
Bug: 'apollo-server-plugin-base' module is not used in Apollo server v4, but required by newrelic

### ISSUE THREAD

**Issue by dhlavaty** [newrelic/newrelic-node-apollo-server-plugin#233]
The requirement of the `apollo-server-plugin-base` module ends with a typescript error during compilation.

## Description

`apollo-server-plugin-base` module is not used in Apollo Server v4 (see https://www.apollographql.com/docs/apollo-server/migration/#packages-merged-into-apolloserver ), but https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/v2.1.0/index.d.ts#L1 still tries to import it. And it ends with a typescript error during compilation.

![Screenshot 2022-12-15 at 13 52 49](https://user-images.githubusercontent.com/513138/207864197-550f26dd-84c2-4491-a7df-eadeabbc1744.png)

## Expected Behavior

Do not use the deprecated `apollo-server-plugin-base` module.

## Env

@newrelic/apollo-server-plugin version 2.1.0
@apollo/server version 4.3.0

**Comment by bizob2828** [comment]
Hi @dhlavaty take a look at the [release notes for 2.1.0](https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/main/NEWS.md#v210-2022-11-10).  For apollo 4 typescript users you have to use the plugin in a different way

**Comment by dhlavaty** [comment]
I use `@newrelic/apollo-server-plugin` exactly as in the release notes.

Typescript's [Module Resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html) picks the `index.d.ts` file automatically. That is Typescript's default behavior. And because [index.d.ts](https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/v2.1.0/index.d.ts?rgh-link-date=2022-12-15T12%3A58%3A04Z#L1) (as you can see) imports `apollo-server-plugin-base`, which is not a `dependency` nor `peerDependency`, it reports it as an error (absolutely correctly in my humble opinion).

So I have several options how to deal with it:
1. modify typescript's `compilerOptions` in `tsconfig.json`
2. use typescripts [path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping)
3. use another [creative workaround](https://stackoverflow.com/questions/41627631/exclude-overwrite-npm-provided-typings/41641001#41641001)
4. install deprecated `apollo-server-plugin-base` as my project's dependency, even though it is not used/needed by Apollo v4 

....but still, all mentioned above are just workarounds to an existing problem.

_Actually, number 4 is the workaround I have chosen to use for now._

**Comment by bizob2828** [comment]
@dhlavaty this [example app](https://github.com/bizob2828/apollo-server-express-nr-example/blob/main/v4/server.ts) shows not needing to install apollo-server-plugin-base.  I'm interested if this works for you. there's not workarounds that you mentioned as far as i can tell.  We had this report a few months ago and we thought we had addressed.

**Comment by Blankll** [comment]
Hi @bizob2828 , any progress on this one? our team also blocked by this issue
