### ISSUE TITLE
`expected_status_codes` newrelic config option not working for apollo errors.

### ISSUE THREAD

**Issue by alex-e-leon** [newrelic/newrelic-node-apollo-server-plugin#239]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
newrelic-node-apollo-server-plugin seems to not be categorizing expected errors properly. My newrelic.js config sets `expected_status_codes: [400]`, but when I look at sample error data in newrelics dashboard, I'm getting errors with properties:

```
error.class: Error
error.expected: false
error.message: HttpError 400
http.statusCode: 400
```

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
I would expect setting `expected_status_codes: [400]` to set `error.expected: true` on 400 errors.

## Steps to Reproduce

See above

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

- node: v16.18.1
- OS: AWS linux
- apollo: `@apollo/server: ^4.2.2`
- apollo-server-plugins: apollo `expressMiddleware` + 
```
[
      ApolloServerPluginDrainHttpServer({httpServer}),
      ApolloServerPluginUsageReporting({sendErrors: {unmodified: true}}),
      ApolloServerPluginLandingPageDisabled()
      newRelicPlugin,
]
```
- express: `express: ^4.18.2`

**Comment by bizob2828** [comment]
@alex-e-leon The config stanza is actually `error_collector.expected_status_codes`.  I tested it on an example application and it worked just fine.  If you have the correct config stanza, can you provide a reproduction case please?

**Comment by alex-e-leon** [comment]
@bizob2828 - 🤦 
Thats looking like it was the issue - I must have missed that info in the documentation. I'll close for now and re-open if I find any other problems.

Thanks for the quick reply!

**Comment by bizob2828** [comment]
@alex-e-leon I can see how it's confusing from the docs as they are nested but only document the values of the child keys.

**Comment by alex-e-leon** [comment]
@bizob2828 - so after deploying the updated config with
```
exports.config = {
  ...
  error_collector: {
    expected_status_codes: [400],
  },
}
```
it looks like 400 errors are still not being marked as expected.

Any other ideas as to what the issue may be?

**Comment by bizob2828** [comment]
@alex-e-leon I cannot reproduce this.  Can you create a reproduction case for me?  Otherwise, for issues like this, I recommend leveraging our support team over at [support.newrelic.com](https://support.newrelic.com) which can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs).

**Comment by alex-e-leon** [comment]
Thanks @bizob2828 - I’ll try the support route first as i feel like it might take quite a bit of work to get a reprodicible project up. If that doesn’t work out though I’ll ping back here. Thanks for your help so far.
