### ISSUE TITLE
Add an option to opt-out of reporting errors to NewRelic

### ISSUE THREAD

**Issue by mscharley** [newrelic/newrelic-node-apollo-server-plugin#253]
## Is your feature request related to a problem? Please describe.

Before finding this plugin, we implemented our own error reporting to NewRelic. There are certain kinds of errors we don't want to report to Newrelic. Now the plugin is causing errors we specifically don't want to send to be sent and generating confusion.

## Feature Description
An option for the plugin which would allow us to opt-out of the built-in error reporting via `noticeError()`.

## Describe Alternatives

1. Some kind of mechanism to ignore certain types of errors, similar to `Array.filter`. Probably something like `(err: Error) => boolean` and only send the error if it returns true.

The proposed opt-out option feels simpler to use and implement though.

## Additional context
N/A

## Priority
Please help us better understand this feature request by choosing a priority from the following options:
Must Have

**Comment by bizob2828** [comment]
@mscharley since errors get collected via our API `noticeError` you unfortunately cannot take advantage of configuration we have to do this automatically.  I will alert our PM of this feature request

**Comment by bizob2828** [comment]
@mscharley you can take advantage of agent configuration to achieve this.  You can either mark errors as expected, or ignore them completely.  Take a look at the configuration options in the `error_collector` stanza in the [docs website](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#error_config)

**Comment by mscharley** [comment]
@bizob2828 Hi, we don't want to disable error collection entirely, we just want to disable error collection from this plugin as we already have other code which reports these errors to newrelic, and does some complex filtering to only send relevant errors, except this plugin is also reporting them and causing issues. Expected errors also isn't a good fit because we have many microservices and we don't want to have to manage the expected errors across many different APM services.

**Comment by bizob2828** [comment]
@mscharley the docs I reference allow you to disable error collection but also allow you to ignore specific error classes, messages, and status codes.  If you do not want to configure this for every application in configuration, you can do so via [server-side configuration](https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/configuration/server-side-agent-configuration/) however only error classes and status codes can be ignored via server side configuration.
