### ISSUE TITLE
Missing typings for optional configuration

### ISSUE THREAD

**Issue by a88zach** [newrelic/newrelic-node-apollo-server-plugin#264]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
The typings are missing configuration options for
* customResolverAttributes
* customOperationAttributes
* captureFieldMetrics

As seen here:  https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/main/index.d.ts#L1

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
The typings should include all configuration options so that the TSC compiler is happy

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
Set up a Typescript project and try to use once of the configuration options listed above

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Node version: 18.17.0
* Typescript version: 5.1.6

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment]
@a88zach nice catch. We need to do a better job of keeping these up to date/checking.

**Comment by bizob2828** [comment]
@a88zach do you mind providing me with a tsconfig for this? I cannot reproduce even before making the fix

**Comment by a88zach** [comment]
@bizob2828 thanks for the fix!  For a future version, I'd like to suggest a slight enhancement to the typings so that we can correctly type the resolver arguments and request context

```
export type NRPluginConfig<U = any, V = any> = {
  captureScalars?: boolean;
  captureIntrospectionQueries?: boolean;
  captureServiceDefinitionQueries?: boolean;
  captureHealthCheckQueries?: boolean;
  customResolverAttributes?: (
    resolverArguments: U
  ) => Record<string, string | number | boolean> | null;
  customOperationAttributes?: (
    requestContext: V
  ) => Record<string, string | number | boolean> | null;
  captureFieldMetrics?: boolean;
};

export default function createPlugin<T, U = any, V = any>(
  config?: NRPluginConfig<U, V>
): T;
```

This would give us strongly typed arguments for the 2 functions

```
expectType<V3Plugin>(createPlugin<V3Plugin>({}));
expectType<V3Plugin>(
  createPlugin<
    V3Plugin,
    { source: any; args: any; contextValue: { bar: string }; info: any },
    { bar: string }
  >({
    captureHealthCheckQueries: true,
    captureScalars: false,
    captureServiceDefinitionQueries: true,
    captureFieldMetrics: true,
    customOperationAttributes: (ctx) => ({
      attr: ctx.bar,
    }),
    customResolverAttributes: (ctx) => ({ attr: ctx.contextValue.bar }),
  })
);
```

**Comment by bizob2828** [comment]
@a88zach PRs are always welcome.  As you can see we aren't writing native typescript so this is always overlooked, I apologize. This is going out shortly has 3.1.1 btw
