### ISSUE TITLE
uninstrumented async-await function in resolver can result in weird middelware naming

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/newrelic-node-apollo-server-plugin#28]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

An uninstrumented async-await function in resolver can result in weird middelware naming: `middleware: <anonymous> //graphql`

Unsure why, but seems something automatically behind the scenes adds `//graphql` to some of the segment/spans when an uninstrumented async function is introduced into a resolver. I'm guessing this is due to transaction state propagated automatically via our promise/async-hooks instrumentation and assumptions made by our web-framework shim. 

It doesn't seem to break anything but is inconsistent and I'm guessing not really meant to be added at this point. Or if it is, likely only to one segment and we should fix so it adds normally. This may require additional state management in our plugin and/or preventing certain actions.

**Comment by bizob2828** [comment]
waiting for @michaelgoin to be present in grooming to discuss this more

**Comment by michaelgoin** [comment]
Not deemed high enough priority to focus on now. Can reopen/replace if get any customer complaints.
