### ISSUE TITLE
Extract query when Apollo is set to persist queries

### ISSUE THREAD

**Issue by carlo-808** [newrelic/newrelic-node-apollo-server-plugin#57]
The Graphql query may not be available off of the GraphQLRequest object when persisted queries are used.

It appears we may be able to access the query off of the `requestContext.source`:
https://github.com/apollographql/apollo-server/blob/2bccec2c5f5adaaf785f13ab98b6e52e22d5b22e/packages/apollo-server-core/src/requestPipeline.ts#L232

It looks like an extension is required to persist queries:
https://github.com/apolloGraphQL/apollo-link-persisted-queries

We may need to update the plugin to detect whether a persisted query is in play and we should populate a query attribute from a consistent location in either case.

**Comment by bizob2828** [comment]
Steps to reproduce:
 * Clone [basic-apollo-federation-demo](https://github.com/bizob2828/basic-apollo-federation-demo)
 * npm ci
 * npm run dev:films
 * run 
```sh
curl -g 'http://localhost:4002?query={__typename}&extensions={"persistedQuery":{"version":1,"sha256Hash":"ecf4edb46db40b5132295c0291d62fb65d6759a9eedfa4d5d612dd5ec54a6b38"}}'
curl -g 'http://localhost:4002?extensions={"persistedQuery":{"version":1,"sha256Hash":"ecf4edb46db40b5132295c0291d62fb65d6759a9eedfa4d5d612dd5ec54a6b38"}}'
```

first one will register this query, and the 2nd will use the sha as the persisted query, second one will rely on the persisted query to properly return the appropriate data
