### ISSUE TITLE
Fill out remaining details of contributing and readme documentation

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/newrelic-node-apollo-server-plugin#6]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Near end of project, fill out specific implementation details to contributing guide(s) and readme to make production ready.

**Comment by nijotz** [comment]
Using https://github.com/newrelic/open-by-default has a template

**Comment by nijotz** [comment]
Readme looks great

**Comment by nijotz** [comment]
`CONTRIBUTING.md` looks quite different from the template in the [open-by-default repo](https://github.com/newrelic/open-by-default/blob/master/CONTRIBUTING.md). Updating now.
