### ISSUE TITLE
Support Apollo Federation

### ISSUE THREAD

**Issue by respectTheCode** [newrelic/newrelic-node-apollo-server-plugin#61]
## Is your feature request related to a problem? Please describe.
It is not clear if this supports Apollo Federation.

## Feature Description
If federation is already supported it should be documented. For example do you add the plugin to the gateway, the services or both. 

If not federation support would be very helpful and it should be documented that it is not supported.

## Describe Alternatives
The only other option is Apollo Studio and it is quite limited.

## Priority
This is a must have for us as we are moving all of our APIs to GraphQL with Apollo Federation.

**Comment by michaelgoin** [comment]
Hi @respectTheCode,

Thank you for the feature request. Apollo Federation wasn't a focus of our initial support, so I'm not sure if it works or not at this time. We went with the plugin approach to try to be as compatible as possible (now and rolling with future changes) with Apollo Server but ultimately it depends on if Apollo uses the exact same plugin model in that situation.

We'll keep track of this to confirm and document in the future.

Thanks!

**Comment by michaelgoin** [comment]
While this mostly already worked as-is, we just shipped improvements in the latest release of the plugin. Notably: transaction naming is now consistent and nesting of external calls from the gateway to sub graphs is now correct in Distributed Trace and Transaction Trace trees.

For more info on setup, see: https://github.com/newrelic/newrelic-node-apollo-server-plugin#apollo-federation-support.
