### ISSUE TITLE
Custom ERROR and supports attributes

### ISSUE THREAD

**Issue by pranshu-07** [newrelic/newrelic-node-apollo-server-plugin#65]
## Is your feature request related to a problem? Please describe.
Can't find how to create a custom error

## Feature Description
Can we have a feature to create a custom error if not there? Please do add documentation to it if present

## Priority
Blocker

**Comment by michaelgoin** [comment]
Hi @pranshu-07 ,

Custom errors would be created via the standard Agent API grabbed via the `newrelic` module. You can find that function mentioned on our API docs page: https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api#noticeError. Although, admittedly it does not describe a whole lot other than the signature.

The function is `noticeError()`. It takes a custom error (or string) and optionally takes custom attributes to apply to the error.

**Comment by pranshu-07** [comment]
Thanks!
