### ISSUE TITLE
Add support for apollo-server-azure-functions

### ISSUE THREAD

**Issue by frank-long** [newrelic/newrelic-node-apollo-server-plugin#66]
## Is your feature request related to a problem? Please describe.
Yes, the plugin is not compatible with apollo-server-azure-functions 

## Feature Description

Would be fantastic if apollo-server-azure-functions was supported
I tested this plugin with apollo-server-azure-functions and I didn't get any errors on initialisation, but I could not see any data being sent to newrelic. Just wondering if there is any roadmap for supporting it

## Priority
Really Want

**Comment by carlo-808** [comment]
Thank you for the feature request, @frank-long ! We currently have no current plans to add azure functions support for the Apollo plugin. We do plan to continually improve support for our plugin and your feedback will help us direct that effort. I will bring this up with our Product Manager to get prioritized.
