### ISSUE TITLE
Cannot read property 'nameState' of null

### ISSUE THREAD

**Issue by frangrolemund** [newrelic/newrelic-node-apollo-server-plugin#67]
## Description

After performing the NewRelic Apollo integration I've started noticing the following in our logs.  This doesn't mean a whole lot but did notice this reported in the [koa integration](https://github.com/newrelic/node-newrelic-koa/issues/32) back in June - wondering if maybe it is related here.  Apologies for the poor format:

`2021-01-29T10:44:44.636Z [WARN] Cannot read property 'nameState' of null Context: {"error":{"message":"Cannot read property 'nameState' of null","extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot read property 'nameState' of null"," at setTransactionName (/usr/cocina/node_modules/@newrelic/apollo-server-plugin/lib/create-plugin.js:314:33)"," at Object.willSendResponse (/usr/cocina/node_modules/@newrelic/apollo-server-plugin/lib/create-plugin.js:224:11)"," at /usr/cocina/node_modules/apollo-server-core/dist/utils/dispatcher.js:21:31"," at Array.map (<anonymous>)"," at Dispatcher.callTargets (/usr/cocina/node_modules/apollo-server-core/dist/utils/dispatcher.js:18:24)"," at Dispatcher.<anonymous> (/usr/cocina/node_modules/apollo-server-core/dist/utils/dispatcher.js:27:43)"," at Generator.next (<anonymous>)"," at /usr/cocina/node_modules/apollo-server-core/dist/utils/dispatcher.js:8:71"," at new Promise (<anonymous>)"," at __awaiter (/usr/cocina/node_modules/apollo-server-core/dist/utils/dispatcher.js:4:12)"]}},"name":"TypeError"}}`

## Expected Behavior

I'd like to not have this error appear in the logs either by changing my integration somehow or updating the package if necessary.

## Steps to Reproduce
Not clear what triggers this error.

## Your Environment

Node v12.14.1
Apollo Server Express 2.17.0

## Additional context

We're also instrumented with AWS Xray as well.

**Comment by michaelgoin** [comment]
Interesting. Really surprised there would be state loss introduced mid-plugin execution.

Do you by chance have any other custom or 3rd-party plugins in use?

We can handle this symptom, though. We can grab the transaction off of the operation segment.

Thank you for letting us know and sorry for the inconvenience!

**Comment by realproven** [comment]
Thanks for looking at this, much appreciated!

We're also instrumenting with AWS Xray at the same time which is operating as custom Express middleware but not an Apollo plugin per-se.  I'm somewhat surprised the two coexist as well as they do and generally speaking I get good information, it is just that there are certain scenarios that throw this error above that I can't nail down.  If it can be masked at least, that would really be awesome.
