### ISSUE TITLE
Add the ability to Ignore based on other details, like Transaction Name

### ISSUE THREAD

**Issue by synackSA** [newrelic/newrelic-node-apollo-server-plugin#78]
## Feature Description
Right now, we're only able to ignore based on URL patterns using the [rules->ignore,](https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#rules_ignore) config settings or the `NEW_RELIC_IGNORING_RULES` ENV variable. This isn't super helpful when dealing with GraphQL, since the URL is pretty much always the same. We would like to be able to ignore certain requests based on a pattern applied against the `transaction.name` (or open it up to more attributes, but personally we would like `transaction.name`). The reason for this is that we don't want to see Introspection Requests in our APM.

## Describe Alternatives
Another way is that we could just have a config setting `ignoreIntrospection` that we can set to `true` or `false` and pass into the config when creating the plugin:
```typescript
const createPlugin = require('@newrelic/apollo-server-plugin')
const plugin = createPlugin({
  ignoreIntrospection: true
})

// imported from supported module
const server = new ApolloServer({
  typeDefs,
  resolvers,
  plugins: [plugin]
})
```

## Priority
Really Want

**Comment by carlo-808** [comment]
Thank you for the feature request, @synackSA , we are more likely to consider the alternative approach of a config item to disable capturing introspection query based transactions. We'll get this prioritized with our PM!
