### ISSUE TITLE
Run apollo-server-hapi versioned tests on Node 16

### ISSUE THREAD

**Issue by bizob2828** [newrelic/newrelic-node-apollo-server-plugin#81]
## Feature Description
During triage of https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/75 it turned out there was a bug with Node.js v16.  In order to allow the PR to be merged, the tests for apollo-server-hapi were pinned to exclude v16: [fix here](https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/77/files#diff-784c71fd342bac523d9980b7de05b6d096135186efc41752fe7a5b95610ff6f7R8).  When Node.js v16 becomes LTS, the tests on should be revisited to see if the fix has been made.

## Additional context
The issue surfaced in Node.js with this PR https://github.com/nodejs/node/pull/33035.  The effect for apollo-server-hapi versioned tests are they just hang: [See affected CI run](https://github.com/newrelic/newrelic-node-apollo-server-plugin/runs/2576730460?check_suite_focus=true).  This is because the readable stream(http request), prematurely is destroyed.  hapi has a listener for this, [handle close](https://github.com/hapijs/hapi/blob/master/lib/request.js#L312), which basically just stops processing the request.  You can reproduce the issue with this [apollo hapi app](https://github.com/bizob2828/apollo-hapi-nr-test) and make this curl request:

```sh
curl --location --request POST 'http://localhost:6000/graphql' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"query GetRoids {\n  asteroids(date: \"2020-08-12\") {\n    id,\n    name,\n    miss_distance_km,\n    close_approach_date,\n    relative_velocity_km_per_hour,\n  }\n}","variables":{}}'
```

The code in Node.js has been reverted: [revert PR](https://github.com/nodejs/node/pull/36647/files), but was only made to v15.  There is still an open issue in Node.js for fixing this https://github.com/nodejs/node/issues/38657, which I assume will happen before v16 becomes LTS.

## Priority
[Must Have]

**Comment by bizob2828** [comment]
apollo-server fixed this but the release hasn't been shipped yet. This PR adds Node 16 support for apollo-server-hapi https://github.com/apollographql/apollo-server/pull/5150.  We will have to lock down the versioned tests regardless to account for this.  It's worth noting we will be possibly dropping support for hapi < 20 for Node 16 for the agent https://github.com/newrelic/node-newrelic/issues/771 but this is a separate plugin and worth a discussion on how to support this plugin in node 16

**Comment by michaelgoin** [comment]
While we have other issues with v3, it looked like this fix had been in v3 so we can potentially tackle this for v3+.

**Comment by michaelgoin** [comment]
Likely requires this to be resolved first: https://github.com/newrelic/newrelic-node-apollo-server-plugin/issues/103
