### ISSUE TITLE
Plugin type error "Cannot read property 'value' of undefined"

### ISSUE THREAD

**Issue by albertstill** [newrelic/newrelic-node-apollo-server-plugin#84]
## Description

I fired a query to to my GraphQL server that had a schema error, a field included an argument that did not exist.

Got

```
{
  "error": {
    "errors": [
      {
        "message": "Cannot read property 'value' of undefined",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR"
        }
      }
    ]
  }
}
```

## Expected Behavior
When I remove the plugin I get:

```
{
  "error": {
    "errors": [
      {
        "message": "Unknown argument \"activityType\" on field \"User.commutes\".",
        "locations": [
          {
            "line": 8,
            "column": 16
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED"
        }
      }
    ]
  }
}
```

## Your Environment

@newrelic/apollo-server-plugin@0.2.0 & Node 14.17.0

## Additional context

I found the line that causes the type error, `selection.name` comes through as undefined sometimes.

https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/ca870ed0bb675b77431d4a0625b237fadddaef41/lib/create-plugin.js#L357

**Comment by carlo-808** [comment]
Thank you @albertstill for submitting this bug along with the additional context. That is super helpful. We'll get this bug prioritized.

**Comment by michaelgoin** [comment]
Just ran into this for the first time with a federated query. Seems like we may need to 'skip' items w/o a name when grabbing from the document/selection set.
