### ISSUE TITLE
Consider allowing customization of Transaction name

### ISSUE THREAD

**Issue by DrewML** [newrelic/newrelic-node-apollo-server-plugin#93]
## Is your feature request related to a problem? Please describe.
When using Batch functionality with Apollo, it becomes difficult to read the Transaction names in New Relic One because of their length.

## Feature Description
We'd like to see the ability to customize the Transaction name. We have different ways of determining uniqueness of operations/clients, so `{deepest-path}` is unnecessary noise for us.

## Describe Alternatives
Ideally we could pass a callback like `computeTransactionName` (to the plugin constructor) that is passed all relevant details (operation name, path, HTTP request object) and could return a String. The default callback, if one is not provided, could be the default functionality from today to prevent breaking changes.

## Additional context
Happy to send a PR if y'all are open to this change.

## Priority
Really Want

**Comment by michaelgoin** [comment]
Hi @DrewML,

Thank you for the issue.

We are actually considering some general naming changes that may make the batch names a little shorter.

That being said, the naming will likely always be somewhat long with the current approach. We've sort of figured we would eventually get some feedback and start using that to inform evolving the batch naming over time.

I'm curious how you are looking to name your batches? Might be useful to help inform things in the future.

As far as this specific request, we'll take under consideration along with the other ways we may evolve the plugin. Another thing we could consider is configuration to drop the path from the name. Some customers definitely need additional details but like you said, others don't.

The good news is, you can get similar functionality with the current API if you want to write your own plugin to load along with ours.

You can use 'didResolveOperation' or 'willSendResponse' handlers to grab data about the GraphQL request. You should then be able to call `newrelic.setTransactionName(<name>)` to override the name with your own custom name.

'didResolveOperation' will only fire for valid queries. If an invalid field is requested, for example, it will not fire. In these cases, the context pased to 'willSendResponse' will also not have all of the details but they can be pulled from the document. Below are a couple links that could prove helpful in how to use plugins and what we do to grab the details currently.

https://www.apollographql.com/docs/apollo-server/integrations/plugins/

https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/main/lib/create-plugin.js#L259-L275

https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/c8782eb28e104c17d2c73217881f7cbc43deab70/lib/create-plugin.js#L307-L318

**Comment by DrewML** [comment]
Hey @michaelgoin, thanks for the ⚡ fast reply!

> I'm curious how you are looking to name your batches? Might be useful to help inform things in the future.

We're using Apollo Client for all of our GraphQL consumers, so all the requests we're looking to report on include a `apollographql-client-name` request header that's unique to each application. We'd prefer to use `OperationName + ClientName` to name our transactions (and use those names with the current batch format, minus `{deepest-path}`).

> As far as this specific request, we'll take under consideration along with the other ways we may evolve the plugin

Thanks! We appreciate it 😄 

> The good news is, you can get similar functionality with the current API if you want to write your own plugin to load along with ours.

Right on - this is _excellent_. We'll take it for a spin.

**Comment by rr0214** [comment]
We will consider improving batch naming. We likely will handle it an alternative way.
